backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true
locale: "pt"
media_folder: public/images
public_folder: images
publish_mode: editorial_workflow
collections:
  - name: "diretorias" # Chapa
    label: "Diretorias"
    folder: "public/posts/diretorias"
    identifier_field: "titulo"
    slug: "diretoria-{{year}}-{{month}}-{{day}}_{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Nome da chapa/ diretoria", name: "titulo", widget: "string" }
      - { label: "Ano de atuação", name: "data", widget: "date" }
      - { label: "Visível ao público", name: "active", widget: "boolean" }
      - label: "Integrantes"
        name: "integrantes"
        widget: list
        fields:
          - { label: "Nome", name: "name", widget: "string" }
          - { label: "Cargo", name: "role", widget: "string" }
          - { label: "Foto", name: "photo", widget: "image" }
          - { label: "Bio", name: "bio", widget: "text" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - {
              label: "Banner da página da diretoria",
              name: "banner",
              widget: "image",
            }
          - {
              label: "Título da página da diretoria",
              name: "title",
              widget: "string",
            }
          - {
              label: "Conteúdo da Página da diretoria (HTML)",
              name: "content",
              widget: "string",
            }

  - name: "noticias"
    label: "Notícias"
    folder: "public/posts/noticias"
    identifier_field: "title"
    slug: "noticia-{{year}}-{{month}}-{{day}}_{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - {
          label: "Banner da notícia (1366x400)",
          name: "banner",
          widget: "image",
        }
      - { label: "Corpo da Notícia (HTML)", name: "content", widget: "string" }
      - { label: "Data", name: "date", widget: "date" }
      - { label: "Autor da Postagem", name: "author", widget: "string" }
      - { label: "Visível ao público", name: "active", widget: "boolean", required: false }
      - { label: "Mostrar no carroussel", name: "carroussel", widget: "boolean", required: false }
      - { label: "Usar redirecionamento - ATENÇÃO: Ao usar esta opção, o card/ banner irá redirecionar o usuário para a url abaixo!", name: "useRedirect", widget: "boolean", required: false }
      - { label: "Url Externa", name: "url", widget: "string", required: false }

  - name: "eventos"
    label: "Eventos"
    folder: "public/posts/eventos"
    identifier_field: "title"
    slug: "evento-{{year}}-{{month}}-{{day}}_{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - {
          label: "Banner do evento (1366x400)",
          name: "banner",
          widget: "image",
        }
      - {
          label: "Descrição do Evento (HTML)",
          name: "content",
          widget: "string",
        }
      - { label: "Data", name: "date", widget: "date" }
      - { label: "Mostrar no carroussel", name: "carroussel", widget: "boolean", required: false }
      - { label: "Usar redirecionamento - ATENÇÃO: Ao usar esta opção, o card/ banner irá redirecionar o usuário para a url abaixo!", name: "useRedirect", widget: "boolean", required: false }
      - { label: "Url Externa", name: "url", widget: "string", required: false }

  - name: "file"
    label: "Arquivos"
    folder: "public/files"
    identifier_field: "nomeArq"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Título - Dê o nome do arquivo",
          name: "title",
          widget: "string",
        }
      - {
          label: "Descrição - Acrescente uma breve explicação sobre o arquivo",
          name: "content",
          widget: "string",
        }
      - {
          label: "Arquivo - Adicione aqui o arquivo",
          name: "file",
          widget: "file",
        }

  - name: "publicacoes"
    label: "Publicações"
    folder: "public/posts/publicacoes"
    identifier_field: "title"
    slug: "publicacao-{{year}}-{{month}}-{{day}}_{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - {
          label: "Banner da publicação (1366x400)",
          name: "banner",
          widget: "image",
        }
      - { label: "Corpo da publicação (HTML)", name: "content", widget: "string" }
      - { label: "Data", name: "date", widget: "date" }
      - { label: "Autor da Postagem", name: "author", widget: "string" }
      - { label: "Visível ao público", name: "active", widget: "boolean", required: false }
      - { label: "Mostrar no carroussel", name: "carroussel", widget: "boolean", required: false }
      - { label: "Usar redirecionamento - ATENÇÃO: Ao usar esta opção, o card/ banner irá redirecionar o usuário para a url abaixo!", name: "useRedirect", widget: "boolean", required: false }
      - { label: "Url Externa", name: "url", widget: "string", required: false }

  - name: "pages"
    label: "Páginas"
    files:
      - label: "Home"
        name: "page_home"
        file: "public/pages/home.json"
        extension: "json"
        format: "json"
        editor:
          preview: false
        fields:
          - label: "Conteúdo do Rodapé"
            name: "footer"
            widget: "object"
            fields:
              - {
                  label: "Instagram",
                  name: "instagram",
                  widget: "string",
                  default: "abenrs_",
                }
              - {
                  label: "Email para contato",
                  name: "email",
                  widget: "string",
                  default: "aben-rs@abennacional.org.br",
                }
              - {
                  label: "Telefone para Contato",
                  name: "phone",
                  widget: "string",
                  default: "(51) 3232-3232",
                }
              - {
                  label: "Facebook",
                  name: "facebook",
                  widget: "string",
                  default: "facebook/aben",
                }

      - label: "Página História"
        name: "page_historia"
        file: "public/pages/historia.json"
        extension: "json"
        format: "json"
        editor:
          preview: true
        fields:
          - { label: "Conteúdo da página (HTML)", name: "content", widget: "string" }

      - label: "Página Sobre"
        name: "page_sobre"
        file: "public/pages/sobre.json"
        extension: "json"
        format: "json"
        editor:
          preview: true
        fields:
          - { label: "Conteúdo da página (HTML)", name: "content", widget: "string" }

      - label: "Banner azul - Associe-se"
        name: "banner_azul"
        file: "public/pages/banner_azul.json"
        extension: "json"
        format: "json"
        editor:
          preview: false
        fields:
          - { label: "Título do Banner Azul", name: "title", widget: "string" }
          - {
              label: "Conteúdo do Banner Azul",
              name: "content",
              widget: "string",
            }
          - { label: "Usar o Banner Azul", name: "active", widget: "boolean" }

      - label: "Contato"
        name: "contato"
        file: "public/pages/contato.json"
        extension: "json"
        format: "json"
        editor:
          preview: false
        fields:
          - { label: "Endereço", name: "end", widget: "string" }
          - { label: "CEP", name: "cep", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Telefone", name: "tel", widget: "string" }

      - label: "Página Associe-se"
        name: "page_associese"
        file: "public/pages/associese.json"
        extension: "json"
        format: "json"
        editor:
          preview: true
        fields:
          - label: "Valores (HTML)"
            name: "content"
            widget: text
