backend:
  #name: test-repo
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: images
collections:
  - name: "diretorias"
    label: "Diretorias"
    folder: "public/posts/diretorias"
    identifier_field: "titulo"
    slug: "diretoria-{{year}}-{{month}}-{{day}}_{{slug}}"
    extension: "json"
    create: true
    fields:
    - { label: "Título", name: "titulo", widget: "string" }
    - { label: "Data", name: "data", widget: "date" }
    - label: 'Integrantes'
      name: "integrantes"
      widget: list
      fields:
        - { label: "Nome", name: "nome", widget: "string" }
        - { label: "Cargo", name: "cargo", widget: "string" }
        - { label: "Foto", name: "foto", widget: "image" }
        - { label: "Bio", name: "bio", widget: "text" }
        - { label: "Email", name: "email", widget: "string" }
      
            