backend:
  #name: test-repo
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true
locale: 'pt'
media_folder: public/images
public_folder: images
publish_mode: editorial_workflow
collections:
  - name: "diretorias"
    label: "Diretorias"
    folder: "public/posts/diretorias"
    identifier_field: "titulo"
    slug: "diretoria-{{year}}-{{month}}-{{day}}_{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: false
    fields:
    - { label: "Nome da chapa/ diretoria", name: "titulo", widget: "string" }
    - { label: "Ano de atuação", name: "data", widget: "date" }
    - { label: "Visível ao público", name: "active",  widget: "boolean" }
    - label: 'Integrantes'
      name: "integrantes"
      widget: list
      fields:
        - { label: "Nome", name: "name", widget: "string" }
        - { label: "Cargo", name: "role", widget: "string" }
        - { label: "Foto", name: "photo", widget: "image" }
        - { label: "Bio", name: "bio", widget: "text" }
        - { label: "Email", name: "email", widget: "string" }
        - { label: "Phone", name: "phone", widget: "string" }

  - name: "noticias"
    label: "Notícas"
    folder: "public/posts/noticias"
    identifier_field: "titulo"
    slug: "noticia-{{year}}-{{month}}-{{day}}_{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: false
    fields:
    - { label: "Título", name: "title", widget: "string" }
    - { label: "Banner da notícia", name: "banner", widget: "image" }
    - { label: "Corpo da Notícia", name: "content", widget: "markdown" }
    - { label: "Data", name: "date", widget: "date" }
    - { label: "Autor da Postagem", name: "author",  widget: "string" }
    - { label: "Mostrar texto no carrousel", name: "show_text",  widget: "boolean" }
    - { label: "Visível ao público", name: "active",  widget: "boolean" }

  - name: "eventos"
    label: "Eventos"
    folder: "public/posts/eventos"
    identifier_field: "titulo"
    slug: "evento-{{year}}-{{month}}-{{day}}_{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: false
    fields:
    - { label: "Título", name: "title", widget: "string" }
    - { label: "Banner do evento", name: "banner", widget: "image" }
    - { label: "Descrição do Evento", name: "description", widget: "markdown" }
    - { label: "Data", name: "date", widget: "date" }
    - { label: "Mostrar texto no carrousel", name: "show_text",  widget: "boolean" }
    - { label: "Visível ao público", name: "active",  widget: "boolean" }

  - name: "anuncios"
    label: "Anúncios"
    folder: "public/posts/anuncios"
    identifier_field: "titulo"
    slug: "anuncio-{{year}}-{{month}}-{{day}}_{{slug}}"
    extension: "json"
    create: true
    editor:
      preview: false
    fields:
    - { label: "Título", name: "title", widget: "string" }
    - { label: "Banner do anúncio", name: "banner", widget: "image" }
    - { label: "Descrição do anúncio", name: "description", widget: "markdown" }
    - { label: "Data", name: "date", widget: "date" }
    - { label: "Mostrar texto no carrousel", name: "show_text",  widget: "boolean" }
    - { label: "Visível ao público", name: "active",  widget: "boolean" }

  - name: "pages"
    label: "Páginas"
    files:
      - label: "Home"
        name: "page_home"
        file: "public/pages/home.json"
        extension: "json"
        format: "json"
        editor:
          preview: false
        fields:
          - label: "Conteúdo do Rodapé"
            name: "footer"
            widget: "object"
            fields:
            - { label: "Instagram", name: "instagram", widget: "string", default: "abenrs_" }
            - { label: "Email para contato", name: "email", widget: "string", default: "aben-rs@abennacional.org.br" }
            - { label: "Telefone para Contato", name: "phone", widget: "string", default: "(51) 3232-3232" }
            - { label: "Facebook", name: "facebook", widget: "string", default: "facebook/aben" }
      - label: "Página História"
        name: "page_historia"
        file: "public/pages/historia.json"
        extension: "json"
        format: "json"
        editor:
          preview: false
        fields:
        - { label: "Conteúdo da página", name: "content", widget: "markdown" }

      - label: "Página Associe-se"
        name: "page_associese"
        file: "public/pages/associese.json"
        extension: "json"
        format: "json"
        editor:
          preview: false
        fields:
          - label: 'Valores - Associado Efetivo'
            name: "valores_efetivo"
            widget: list
            fields:
              - { label: "Categoria", name: "categoria", widget: "string", default: "Enfermeiro" }
              - { label: "Valor", name: "valor", widget: "string", default: "R$ 00,00" }
          - label: 'Valores - Associado Estrangeiro'
            name: "valores_estrangeiro"
            widget: list
            fields:
              - { label: "Categoria", name: "categoria", widget: "string", default: "Enfermeiro" }
              - { label: "Valor", name: "valor", widget: "string", default: "R$ 00,00" }
    